---

- name: |
    4.1.2.1 | PATCH | Ensure audit log storage size is configured
    4.1.2.2 | PATCH | Ensure audit logs are not automatically deleted
    4.1.2.3 | PATCH | Ensure system is disabled when audit logs are full
  lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "^{{ item }}( |=)"
      line: "{{ item }} = {{ rhel8cis_auditd[item] }}"
  loop: "{{ rhel8cis_auditd.keys() }}"
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_2_1
      - rhel8cis_rule_4_1_2_2
      - rhel8cis_rule_4_1_2_3
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - auditd
      - rule_4.1.2.1
      - rule_4.1.2.2
      - rule_4.1.2.3
